// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package infoviewer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Alliance-1]
	_ = x[Bloodline-2]
	_ = x[Character-3]
	_ = x[Constellation-4]
	_ = x[Corporation-5]
	_ = x[Faction-6]
	_ = x[Location-7]
	_ = x[Race-8]
	_ = x[Region-9]
	_ = x[SolarSystem-10]
	_ = x[Type-11]
}

const _Kind_name = "UndefinedAllianceBloodlineCharacterConstellationCorporationFactionLocationRaceRegionSolarSystemType"

var _Kind_index = [...]uint8{0, 9, 17, 26, 35, 48, 59, 66, 74, 78, 84, 95, 99}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
