ignore:
  - "evebuddy/internal/app/icons"
  - "internal/app/storage/queries"
  - "internal/app/storage/testutil"
  - "internal/eveicon/mapping.go"
  - "internal/eveicon/resource.go"
  - "internal/eveicon/schematic.go"
  - "tools"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
