Website = "https://github.com/ErikKalkoken/evebuddy"

[Details]
  Icon = "icon.png"
  Name = "EVE Buddy"
  ID = "io.github.erikkalkoken.evebuddy"
  Version = "0.9.3"
  Build = 1

[Release]
  BuildName = "evebuddy"
  ContentRating = "oars-1.1"
  Description = "<p>A companion app for Eve Online players. Please see website for details.</p>"
  License = "MIT"
  Screenshots = "https://cdn.imgpile.com/f/aD27GDt_xl.png"

[LinuxAndBSD]
  GenericName = "Eve Online Tool"
  Categories = ["Game"]
  Comment = "A companion app for Eve Online players"
  Keywords = ["Eve Online", "characters"]
