Website = "https://github.com/ErikKalkoken/evebuddy"

[Details]
  Icon = "icon.png"
  Name = "EVE Buddy"
  ID = "io.github.erikkalkoken.evebuddy"
  Version = "0.38.0"
  Build = 0

[Release]
  BuildName = "evebuddy"
  ContentRating = "oars-1.1"
  Description = "<p>EVE Buddy is a multi-platform companion app for Eve Online players available on Windows, macOS, Linux and Android. Please see website for details.</p>"
  License = "MIT"
  Screenshots = "https://cdn.imgpile.com/f/aD27GDt_xl.png"

[LinuxAndBSD]
  GenericName = "Eve Online Tool"
  Categories = ["Game"]
  Comment = "A multi-platform companion app for Eve Online players"
  Keywords = ["Eve Online", "characters"]
