CREATE TABLE eve_corporations (
    id INTEGER PRIMARY KEY NOT NULL,
    alliance_id INTEGER,
    ceo_id INTEGER,
    creator_id INTEGER,
    date_founded DATETIME,
    description TEXT NOT NULL,
    faction_id INTEGER,
    home_station_id INTEGER,
    member_count INTEGER NOT NULL,
    name TEXT NOT NULL,
    shares INTEGER,
    tax_rate REAL NOT NULL,
    ticker TEXT NOT NULL,
    url TEXT NOT NULL,
    war_eligible BOOL NOT NULL,
    FOREIGN KEY (alliance_id) REFERENCES eve_entities (id) ON DELETE SET NULL,
    FOREIGN KEY (ceo_id) REFERENCES eve_entities (id) ON DELETE SET NULL,
    FOREIGN KEY (creator_id) REFERENCES eve_entities (id) ON DELETE SET NULL,
    FOREIGN KEY (faction_id) REFERENCES eve_entities (id) ON DELETE SET NULL,
    FOREIGN KEY (home_station_id) REFERENCES eve_entities (id) ON DELETE SET NULL
);
