package evenotification

import (
	"maps"
	"slices"
)

type Category uint

const (
	Bills Category = iota + 1
	FactionWarfare
	Contacts
	Corporate
	Insurance
	Insurgencies
	MoonMining
	Miscellaneous
	Old
	Sovereignty
	Structure
	War
	Unknown
)

var category2Name = map[Category]string{
	Bills:          "Bills",
	FactionWarfare: "Faction Warfare",
	Contacts:       "Contacts",
	Corporate:      "Corporate",
	Insurance:      "Insurance",
	Insurgencies:   "Insurgencies",
	Miscellaneous:  "Miscellaneous",
	MoonMining:     "Moon Mining",
	Old:            "Old",
	Sovereignty:    "Sovereignty",
	Structure:      "Structure",
	War:            "War",
}

func (c Category) String() string {
	return category2Name[c]
}

// Categories returns a slice of all categories in alphabetical order.
func Categories() []Category {
	return slices.Sorted(maps.Keys(category2Name))
}

var Type2category = map[Type]Category{
	AcceptedAlly:                              War,
	AcceptedSurrender:                         War,
	AgentRetiredTrigravian:                    Unknown,
	AllAnchoringMsg:                           Sovereignty,
	AllMaintenanceBillMsg:                     Bills,
	AllStructureInvulnerableMsg:               Structure,
	AllStructVulnerableMsg:                    Structure,
	AllWarCorpJoinedAllianceMsg:               War,
	AllWarDeclaredMsg:                         War,
	AllWarInvalidatedMsg:                      War,
	AllWarRetractedMsg:                        War,
	AllWarSurrenderMsg:                        War,
	AllianceCapitalChanged:                    Miscellaneous,
	AllianceWarDeclaredV2:                     War,
	AllyContractCancelled:                     War,
	AllyJoinedWarAggressorMsg:                 War,
	AllyJoinedWarAllyMsg:                      War,
	AllyJoinedWarDefenderMsg:                  War,
	BattlePunishFriendlyFire:                  Unknown,
	BillOutOfMoneyMsg:                         Bills,
	BillPaidCorpAllMsg:                        Bills,
	BountyClaimMsg:                            Unknown,
	BountyESSShared:                           Unknown,
	BountyESSTaken:                            Unknown,
	BountyPlacedAlliance:                      Unknown,
	BountyPlacedChar:                          Unknown,
	BountyPlacedCorp:                          Unknown,
	BountyYourBountyClaimed:                   Unknown,
	BuddyConnectContactAdd:                    Unknown,
	CharAppAcceptMsg:                          Corporate,
	CharAppRejectMsg:                          Corporate,
	CharAppWithdrawMsg:                        Corporate,
	CharLeftCorpMsg:                           Corporate,
	CharMedalMsg:                              Corporate,
	CharTerminationMsg:                        Corporate,
	CloneActivationMsg:                        Unknown,
	CloneActivationMsg2:                       Unknown,
	CloneMovedMsg:                             Unknown,
	CloneRevokedMsg1:                          Unknown,
	CloneRevokedMsg2:                          Unknown,
	CombatOperationFinished:                   Unknown,
	ContactAdd:                                Contacts,
	ContactEdit:                               Contacts,
	ContainerPasswordMsg:                      Unknown,
	ContractRegionChangedToPochven:            Unknown,
	CorpAllBillMsg:                            Bills,
	CorpAppAcceptMsg:                          Corporate,
	CorpAppInvitedMsg:                         Corporate,
	CorpAppNewMsg:                             Corporate,
	CorpAppRejectCustomMsg:                    Corporate,
	CorpAppRejectMsg:                          Corporate,
	CorpBecameWarEligible:                     Corporate,
	CorpDividendMsg:                           Corporate,
	CorpFriendlyFireDisableTimerCompleted:     Corporate,
	CorpFriendlyFireDisableTimerStarted:       Corporate,
	CorpFriendlyFireEnableTimerCompleted:      Corporate,
	CorpFriendlyFireEnableTimerStarted:        Corporate,
	CorpKicked:                                Corporate,
	CorpLiquidationMsg:                        Corporate,
	CorpNewCEOMsg:                             Corporate,
	CorpNewsMsg:                               Corporate,
	CorpNoLongerWarEligible:                   Corporate,
	CorpOfficeExpirationMsg:                   Corporate,
	CorpStructLostMsg:                         Corporate,
	CorpTaxChangeMsg:                          Corporate,
	CorpVoteCEORevokedMsg:                     Corporate,
	CorpVoteMsg:                               Corporate,
	CorpWarDeclaredMsg:                        War,
	CorpWarDeclaredV2:                         War,
	CorpWarFightingLegalMsg:                   War,
	CorpWarInvalidatedMsg:                     War,
	CorpWarRetractedMsg:                       War,
	CorpWarSurrenderMsg:                       War,
	CorporationGoalClosed:                     Corporate,
	CorporationGoalCompleted:                  Corporate,
	CorporationGoalCreated:                    Corporate,
	CorporationGoalNameChange:                 Corporate,
	CorporationLeft:                           Corporate,
	CustomsMsg:                                Miscellaneous,
	DeclareWar:                                War,
	DistrictAttacked:                          War,
	DustAppAcceptedMsg:                        Miscellaneous,
	ESSMainBankLink:                           Unknown,
	EntosisCaptureStarted:                     Sovereignty,
	ExpertSystemExpired:                       Miscellaneous,
	ExpertSystemExpiryImminent:                Miscellaneous,
	FWAllianceKickMsg:                         FactionWarfare,
	FWAllianceWarningMsg:                      FactionWarfare,
	FWCharKickMsg:                             FactionWarfare,
	FWCharRankGainMsg:                         FactionWarfare,
	FWCharRankLossMsg:                         FactionWarfare,
	FWCharWarningMsg:                          FactionWarfare,
	FWCorpJoinMsg:                             FactionWarfare,
	FWCorpKickMsg:                             FactionWarfare,
	FWCorpLeaveMsg:                            FactionWarfare,
	FWCorpWarningMsg:                          FactionWarfare,
	FacWarCorpJoinRequestMsg:                  FactionWarfare,
	FacWarCorpJoinWithdrawMsg:                 FactionWarfare,
	FacWarCorpLeaveRequestMsg:                 FactionWarfare,
	FacWarCorpLeaveWithdrawMsg:                FactionWarfare,
	FacWarLPDisqualifiedEvent:                 FactionWarfare,
	FacWarLPDisqualifiedKill:                  FactionWarfare,
	FacWarLPPayoutEvent:                       FactionWarfare,
	FacWarLPPayoutKill:                        FactionWarfare,
	GameTimeAdded:                             Unknown,
	GameTimeReceived:                          Unknown,
	GameTimeSent:                              Unknown,
	GiftReceived:                              Unknown,
	IHubDestroyedByBillFailure:                Sovereignty,
	IncursionCompletedMsg:                     Unknown,
	IndustryOperationFinished:                 Unknown,
	IndustryTeamAuctionLost:                   Unknown,
	IndustryTeamAuctionWon:                    Unknown,
	InfrastructureHubBillAboutToExpire:        Unknown,
	InsuranceExpirationMsg:                    Unknown,
	InsuranceFirstShipMsg:                     Unknown,
	InsuranceInvalidatedMsg:                   Unknown,
	InsuranceIssuedMsg:                        Unknown,
	InsurancePayoutMsg:                        Unknown,
	InvasionCompletedMsg:                      Unknown,
	InvasionSystemLogin:                       Unknown,
	InvasionSystemStart:                       Unknown,
	JumpCloneDeletedMsg1:                      Unknown,
	JumpCloneDeletedMsg2:                      Unknown,
	KillReportFinalBlow:                       Unknown,
	KillReportVictim:                          Unknown,
	KillRightAvailable:                        Unknown,
	KillRightAvailableOpen:                    Unknown,
	KillRightEarned:                           Unknown,
	KillRightUnavailable:                      Unknown,
	KillRightUnavailableOpen:                  Unknown,
	KillRightUsed:                             Unknown,
	LPAutoRedeemed:                            Unknown,
	LocateCharMsg:                             Unknown,
	MadeWarMutual:                             Unknown,
	MercOfferRetractedMsg:                     War,
	MercOfferedNegotiationMsg:                 War,
	MissionCanceledTriglavian:                 Unknown,
	MissionOfferExpirationMsg:                 Unknown,
	MissionTimeoutMsg:                         Unknown,
	MoonminingAutomaticFracture:               MoonMining,
	MoonminingExtractionCancelled:             MoonMining,
	MoonminingExtractionFinished:              MoonMining,
	MoonminingExtractionStarted:               MoonMining,
	MoonminingLaserFired:                      MoonMining,
	MutualWarExpired:                          War,
	MutualWarInviteAccepted:                   War,
	MutualWarInviteRejected:                   War,
	MutualWarInviteSent:                       War,
	NPCStandingsGained:                        Unknown,
	NPCStandingsLost:                          Unknown,
	OfferToAllyRetracted:                      War,
	OfferedSurrender:                          War,
	OfferedToAlly:                             War,
	OfficeLeaseCanceledInsufficientStandings:  Corporate,
	OldLscMessages:                            Unknown,
	OperationFinished:                         Unknown,
	OrbitalAttacked:                           Structure,
	OrbitalReinforced:                         Structure,
	OwnershipTransferred:                      Structure,
	RaffleCreated:                             Unknown,
	RaffleExpired:                             Unknown,
	RaffleFinished:                            Unknown,
	ReimbursementMsg:                          Unknown,
	ResearchMissionAvailableMsg:               Unknown,
	RetractsWar:                               War,
	SPAutoRedeemed:                            Unknown,
	SeasonalChallengeCompleted:                Unknown,
	SkinSequencingCompleted:                   Unknown,
	SkyhookDeployed:                           Structure,
	SkyhookDestroyed:                          Structure,
	SkyhookLostShields:                        Structure,
	SkyhookOnline:                             Structure,
	SkyhookUnderAttack:                        Structure,
	SovAllClaimAcquiredMsg:                    Sovereignty,
	SovAllClaimLostMsg:                        Sovereignty,
	SovCommandNodeEventStarted:                Sovereignty,
	SovCorpBillLateMsg:                        Sovereignty,
	SovCorpClaimFailMsg:                       Sovereignty,
	SovDisruptorMsg:                           Sovereignty,
	SovStationEnteredFreeport:                 Sovereignty,
	SovStructureDestroyed:                     Sovereignty,
	SovStructureReinforced:                    Sovereignty,
	SovStructureSelfDestructCancel:            Sovereignty,
	SovStructureSelfDestructFinished:          Sovereignty,
	SovStructureSelfDestructRequested:         Sovereignty,
	SovereigntyIHDamageMsg:                    Sovereignty,
	SovereigntySBUDamageMsg:                   Sovereignty,
	SovereigntyTCUDamageMsg:                   Sovereignty,
	StationAggressionMsg1:                     Unknown,
	StationAggressionMsg2:                     Unknown,
	StationConquerMsg:                         Unknown,
	StationServiceDisabled:                    Unknown,
	StationServiceEnabled:                     Unknown,
	StationStateChangeMsg:                     Unknown,
	StoryLineMissionAvailableMsg:              Unknown,
	StructureAnchoring:                        Structure,
	StructureCourierContractChanged:           Structure,
	StructureDestroyed:                        Structure,
	StructureFuelAlert:                        Structure,
	StructureImpendingAbandonmentAssetsAtRisk: Structure,
	StructureItemsDelivered:                   Structure,
	StructureItemsMovedToSafety:               Structure,
	StructureLostArmor:                        Structure,
	StructureLostShields:                      Structure,
	StructureLowReagentsAlert:                 Structure,
	StructureNoReagentsAlert:                  Structure,
	StructureOnline:                           Structure,
	StructurePaintPurchased:                   Structure,
	StructureServicesOffline:                  Structure,
	StructureUnanchoring:                      Structure,
	StructureUnderAttack:                      Structure,
	StructureWentHighPower:                    Structure,
	StructureWentLowPower:                     Structure,
	StructuresJobsCancelled:                   Structure,
	StructuresJobsPaused:                      Structure,
	StructuresReinforcementChanged:            Structure,
	TowerAlertMsg:                             Structure,
	TowerResourceAlertMsg:                     Structure,
	TransactionReversalMsg:                    Unknown,
	TutorialMsg:                               Unknown,
	WarAdopted:                                War,
	WarAllyInherited:                          War,
	WarAllyOfferDeclinedMsg:                   War,
	WarConcordInvalidates:                     War,
	WarDeclared:                               War,
	WarEndedHqSecurityDrop:                    War,
	WarHQRemovedFromSpace:                     War,
	WarInherited:                              War,
	WarInvalid:                                War,
	WarRetracted:                              War,
	WarRetractedByConcord:                     War,
	WarSurrenderDeclinedMsg:                   War,
	WarSurrenderOfferMsg:                      War,
}

var CategoryTypes map[Category][]Type

func init() {
	CategoryTypes = make(map[Category][]Type)
	for type_, category := range Type2category {
		c := category
		if category == Unknown {
			c = Miscellaneous
		}
		CategoryTypes[c] = append(CategoryTypes[c], type_)
	}
}
