package app

type NotificationCategory int

const (
	categoryUnknown NotificationCategory = iota
	CategoryBills
	CategoryFactionWarfare
	CategoryContacts
	CategoryCorporate
	CategoryInsurance
	CategoryInsurgencies
	CategoryMiscellaneous
	CategoryOld
	CategorySovereignty
	CategoryStructure
	CategoryWar
)

var NotificationCategoryNames = map[NotificationCategory]string{
	CategoryBills:          "Bills",
	CategoryFactionWarfare: "Faction Warfare",
	CategoryContacts:       "Contacts",
	CategoryCorporate:      "Corporate",
	CategoryInsurance:      "Insurance",
	CategoryInsurgencies:   "Insurgencies",
	CategoryMiscellaneous:  "Miscellaneous",
	CategoryOld:            "Old",
	CategorySovereignty:    "Sovereignty",
	CategoryStructure:      "Structure",
	CategoryWar:            "War",
}

var Notification2category = map[string]NotificationCategory{
	"AcceptedAlly":                              CategoryWar,
	"AcceptedSurrender":                         CategoryWar,
	"AgentRetiredTrigravian":                    categoryUnknown,
	"AllAnchoringMsg":                           CategorySovereignty,
	"AllMaintenanceBillMsg":                     CategoryBills,
	"AllStrucInvulnerableMsg":                   CategoryStructure,
	"AllStructVulnerableMsg":                    CategoryStructure,
	"AllWarCorpJoinedAllianceMsg":               CategoryWar,
	"AllWarDeclaredMsg":                         CategoryWar,
	"AllWarInvalidatedMsg":                      CategoryWar,
	"AllWarRetractedMsg":                        CategoryWar,
	"AllWarSurrenderMsg":                        CategoryWar,
	"AllianceCapitalChanged":                    CategoryMiscellaneous,
	"AllianceWarDeclaredV2":                     CategoryWar,
	"AllyContractCancelled":                     CategoryWar,
	"AllyJoinedWarAggressorMsg":                 CategoryWar,
	"AllyJoinedWarAllyMsg":                      CategoryWar,
	"AllyJoinedWarDefenderMsg":                  CategoryWar,
	"BattlePunishFriendlyFire":                  categoryUnknown,
	"BillOutOfMoneyMsg":                         CategoryBills,
	"BillPaidCorpAllMsg":                        CategoryBills,
	"BountyClaimMsg":                            categoryUnknown,
	"BountyESSShared":                           categoryUnknown,
	"BountyESSTaken":                            categoryUnknown,
	"BountyPlacedAlliance":                      categoryUnknown,
	"BountyPlacedChar":                          categoryUnknown,
	"BountyPlacedCorp":                          categoryUnknown,
	"BountyYourBountyClaimed":                   categoryUnknown,
	"BuddyConnectContactAdd":                    categoryUnknown,
	"CharAppAcceptMsg":                          CategoryCorporate,
	"CharAppRejectMsg":                          CategoryCorporate,
	"CharAppWithdrawMsg":                        CategoryCorporate,
	"CharLeftCorpMsg":                           CategoryCorporate,
	"CharMedalMsg":                              CategoryCorporate,
	"CharTerminationMsg":                        CategoryCorporate,
	"CloneActivationMsg":                        categoryUnknown,
	"CloneActivationMsg2":                       categoryUnknown,
	"CloneMovedMsg":                             categoryUnknown,
	"CloneRevokedMsg1":                          categoryUnknown,
	"CloneRevokedMsg2":                          categoryUnknown,
	"CombatOperationFinished":                   categoryUnknown,
	"ContactAdd":                                CategoryContacts,
	"ContactEdit":                               CategoryContacts,
	"ContainerPasswordMsg":                      categoryUnknown,
	"ContractRegionChangedToPochven":            categoryUnknown,
	"CorpAllBillMsg":                            CategoryBills,
	"CorpAppAcceptMsg":                          CategoryCorporate,
	"CorpAppInvitedMsg":                         CategoryCorporate,
	"CorpAppNewMsg":                             CategoryCorporate,
	"CorpAppRejectCustomMsg":                    CategoryCorporate,
	"CorpAppRejectMsg":                          CategoryCorporate,
	"CorpBecameWarEligible":                     CategoryCorporate,
	"CorpDividendMsg":                           CategoryCorporate,
	"CorpFriendlyFireDisableTimerCompleted":     CategoryCorporate,
	"CorpFriendlyFireDisableTimerStarted":       CategoryCorporate,
	"CorpFriendlyFireEnableTimerCompleted":      CategoryCorporate,
	"CorpFriendlyFireEnableTimerStarted":        CategoryCorporate,
	"CorpKicked":                                CategoryCorporate,
	"CorpLiquidationMsg":                        CategoryCorporate,
	"CorpNewCEOMsg":                             CategoryCorporate,
	"CorpNewsMsg":                               CategoryCorporate,
	"CorpNoLongerWarEligible":                   CategoryCorporate,
	"CorpOfficeExpirationMsg":                   CategoryCorporate,
	"CorpStructLostMsg":                         CategoryCorporate,
	"CorpTaxChangeMsg":                          CategoryCorporate,
	"CorpVoteCEORevokedMsg":                     CategoryCorporate,
	"CorpVoteMsg":                               CategoryCorporate,
	"CorpWarDeclaredMsg":                        CategoryWar,
	"CorpWarDeclaredV2":                         CategoryWar,
	"CorpWarFightingLegalMsg":                   CategoryWar,
	"CorpWarInvalidatedMsg":                     CategoryWar,
	"CorpWarRetractedMsg":                       CategoryWar,
	"CorpWarSurrenderMsg":                       CategoryWar,
	"CorporationGoalClosed":                     CategoryCorporate,
	"CorporationGoalCompleted":                  CategoryCorporate,
	"CorporationGoalCreated":                    CategoryCorporate,
	"CorporationGoalNameChange":                 CategoryCorporate,
	"CorporationLeft":                           CategoryCorporate,
	"CustomsMsg":                                CategoryMiscellaneous,
	"DeclareWar":                                CategoryWar,
	"DistrictAttacked":                          CategoryWar,
	"DustAppAcceptedMsg":                        CategoryMiscellaneous,
	"ESSMainBankLink":                           categoryUnknown,
	"EntosisCaptureStarted":                     CategorySovereignty,
	"ExpertSystemExpired":                       CategoryMiscellaneous,
	"ExpertSystemExpiryImminent":                CategoryMiscellaneous,
	"FWAllianceKickMsg":                         CategoryFactionWarfare,
	"FWAllianceWarningMsg":                      CategoryFactionWarfare,
	"FWCharKickMsg":                             CategoryFactionWarfare,
	"FWCharRankGainMsg":                         CategoryFactionWarfare,
	"FWCharRankLossMsg":                         CategoryFactionWarfare,
	"FWCharWarningMsg":                          CategoryFactionWarfare,
	"FWCorpJoinMsg":                             CategoryFactionWarfare,
	"FWCorpKickMsg":                             CategoryFactionWarfare,
	"FWCorpLeaveMsg":                            CategoryFactionWarfare,
	"FWCorpWarningMsg":                          CategoryFactionWarfare,
	"FacWarCorpJoinRequestMsg":                  CategoryFactionWarfare,
	"FacWarCorpJoinWithdrawMsg":                 CategoryFactionWarfare,
	"FacWarCorpLeaveRequestMsg":                 CategoryFactionWarfare,
	"FacWarCorpLeaveWithdrawMsg":                CategoryFactionWarfare,
	"FacWarLPDisqualifiedEvent":                 CategoryFactionWarfare,
	"FacWarLPDisqualifiedKill":                  CategoryFactionWarfare,
	"FacWarLPPayoutEvent":                       CategoryFactionWarfare,
	"FacWarLPPayoutKill":                        CategoryFactionWarfare,
	"GameTimeAdded":                             categoryUnknown,
	"GameTimeReceived":                          categoryUnknown,
	"GameTimeSent":                              categoryUnknown,
	"GiftReceived":                              categoryUnknown,
	"IHubDestroyedByBillFailure":                CategorySovereignty,
	"IncursionCompletedMsg":                     categoryUnknown,
	"IndustryOperationFinished":                 categoryUnknown,
	"IndustryTeamAuctionLost":                   categoryUnknown,
	"IndustryTeamAuctionWon":                    categoryUnknown,
	"InfrastructureHubBillAboutToExpire":        categoryUnknown,
	"InsuranceExpirationMsg":                    categoryUnknown,
	"InsuranceFirstShipMsg":                     categoryUnknown,
	"InsuranceInvalidatedMsg":                   categoryUnknown,
	"InsuranceIssuedMsg":                        categoryUnknown,
	"InsurancePayoutMsg":                        categoryUnknown,
	"InvasionCompletedMsg":                      categoryUnknown,
	"InvasionSystemLogin":                       categoryUnknown,
	"InvasionSystemStart":                       categoryUnknown,
	"JumpCloneDeletedMsg1":                      categoryUnknown,
	"JumpCloneDeletedMsg2":                      categoryUnknown,
	"KillReportFinalBlow":                       categoryUnknown,
	"KillReportVictim":                          categoryUnknown,
	"KillRightAvailable":                        categoryUnknown,
	"KillRightAvailableOpen":                    categoryUnknown,
	"KillRightEarned":                           categoryUnknown,
	"KillRightUnavailable":                      categoryUnknown,
	"KillRightUnavailableOpen":                  categoryUnknown,
	"KillRightUsed":                             categoryUnknown,
	"LPAutoRedeemed":                            categoryUnknown,
	"LocateCharMsg":                             categoryUnknown,
	"MadeWarMutual":                             categoryUnknown,
	"MercOfferRetractedMsg":                     CategoryWar,
	"MercOfferedNegotiationMsg":                 CategoryWar,
	"MissionCanceledTriglavian":                 categoryUnknown,
	"MissionOfferExpirationMsg":                 categoryUnknown,
	"MissionTimeoutMsg":                         categoryUnknown,
	"MoonminingAutomaticFracture":               CategoryStructure,
	"MoonminingExtractionCancelled":             CategoryStructure,
	"MoonminingExtractionFinished":              CategoryStructure,
	"MoonminingExtractionStarted":               CategoryStructure,
	"MoonminingLaserFired":                      CategoryStructure,
	"MutualWarExpired":                          CategoryWar,
	"MutualWarInviteAccepted":                   CategoryWar,
	"MutualWarInviteRejected":                   CategoryWar,
	"MutualWarInviteSent":                       CategoryWar,
	"NPCStandingsGained":                        categoryUnknown,
	"NPCStandingsLost":                          categoryUnknown,
	"OfferToAllyRetracted":                      CategoryWar,
	"OfferedSurrender":                          CategoryWar,
	"OfferedToAlly":                             CategoryWar,
	"OfficeLeaseCanceledInsufficientStandings":  CategoryCorporate,
	"OldLscMessages":                            categoryUnknown,
	"OperationFinished":                         categoryUnknown,
	"OrbitalAttacked":                           CategoryStructure,
	"OrbitalReinforced":                         CategoryStructure,
	"OwnershipTransferred":                      CategoryStructure,
	"RaffleCreated":                             categoryUnknown,
	"RaffleExpired":                             categoryUnknown,
	"RaffleFinished":                            categoryUnknown,
	"ReimbursementMsg":                          categoryUnknown,
	"ResearchMissionAvailableMsg":               categoryUnknown,
	"RetractsWar":                               CategoryWar,
	"SPAutoRedeemed":                            categoryUnknown,
	"SeasonalChallengeCompleted":                categoryUnknown,
	"SkinSequencingCompleted":                   categoryUnknown,
	"SkyhookDeployed":                           CategoryStructure,
	"SkyhookDestroyed":                          CategoryStructure,
	"SkyhookLostShields":                        CategoryStructure,
	"SkyhookOnline":                             CategoryStructure,
	"SkyhookUnderAttack":                        CategoryStructure,
	"SovAllClaimAquiredMsg":                     CategorySovereignty,
	"SovAllClaimLostMsg":                        CategorySovereignty,
	"SovCommandNodeEventStarted":                CategorySovereignty,
	"SovCorpBillLateMsg":                        CategorySovereignty,
	"SovCorpClaimFailMsg":                       CategorySovereignty,
	"SovDisruptorMsg":                           CategorySovereignty,
	"SovStationEnteredFreeport":                 CategorySovereignty,
	"SovStructureDestroyed":                     CategorySovereignty,
	"SovStructureReinforced":                    CategorySovereignty,
	"SovStructureSelfDestructCancel":            CategorySovereignty,
	"SovStructureSelfDestructFinished":          CategorySovereignty,
	"SovStructureSelfDestructRequested":         CategorySovereignty,
	"SovereigntyIHDamageMsg":                    CategorySovereignty,
	"SovereigntySBUDamageMsg":                   CategorySovereignty,
	"SovereigntyTCUDamageMsg":                   CategorySovereignty,
	"StationAggressionMsg1":                     categoryUnknown,
	"StationAggressionMsg2":                     categoryUnknown,
	"StationConquerMsg":                         categoryUnknown,
	"StationServiceDisabled":                    categoryUnknown,
	"StationServiceEnabled":                     categoryUnknown,
	"StationStateChangeMsg":                     categoryUnknown,
	"StoryLineMissionAvailableMsg":              categoryUnknown,
	"StructureAnchoring":                        CategoryStructure,
	"StructureCourierContractChanged":           categoryUnknown,
	"StructureDestroyed":                        CategoryStructure,
	"StructureFuelAlert":                        CategoryStructure,
	"StructureImpendingAbandonmentAssetsAtRisk": CategoryStructure,
	"StructureItemsDelivered":                   CategoryStructure,
	"StructureItemsMovedToSafety":               CategoryStructure,
	"StructureLostArmor":                        CategoryStructure,
	"StructureLostShields":                      CategoryStructure,
	"StructureLowReagentsAlert":                 categoryUnknown,
	"StructureNoReagentsAlert":                  categoryUnknown,
	"StructureOnline":                           CategoryStructure,
	"StructurePaintPurchased":                   categoryUnknown,
	"StructureServicesOffline":                  CategoryStructure,
	"StructureUnanchoring":                      CategoryStructure,
	"StructureUnderAttack":                      CategoryStructure,
	"StructureWentHighPower":                    CategoryStructure,
	"StructureWentLowPower":                     CategoryStructure,
	"StructuresJobsCancelled":                   categoryUnknown,
	"StructuresJobsPaused":                      categoryUnknown,
	"StructuresReinforcementChanged":            CategoryStructure,
	"TowerAlertMsg":                             CategoryStructure,
	"TowerResourceAlertMsg":                     CategoryStructure,
	"TransactionReversalMsg":                    categoryUnknown,
	"TutorialMsg":                               categoryUnknown,
	"WarAdopted":                                CategoryWar,
	"WarAllyInherited":                          CategoryWar,
	"WarAllyOfferDeclinedMsg":                   CategoryWar,
	"WarConcordInvalidates":                     CategoryWar,
	"WarDeclared":                               CategoryWar,
	"WarEndedHqSecurityDrop":                    CategoryWar,
	"WarHQRemovedFromSpace":                     CategoryWar,
	"WarInherited":                              CategoryWar,
	"WarInvalid":                                CategoryWar,
	"WarRetracted":                              CategoryWar,
	"WarRetractedByConcord":                     CategoryWar,
	"WarSurrenderDeclinedMsg":                   CategoryWar,
	"WarSurrenderOfferMsg":                      CategoryWar,
}

var NotificationCategoryTypes map[NotificationCategory][]string

func init() {
	NotificationCategoryTypes = make(map[NotificationCategory][]string)
	for name, category := range Notification2category {
		c := category
		if category == categoryUnknown {
			c = CategoryMiscellaneous
		}
		NotificationCategoryTypes[c] = append(NotificationCategoryTypes[c], name)
	}
}
