// Code generated by ifacemaker; DO NOT EDIT.

package app

import (
	"time"

	"fyne.io/fyne/v2"
	"github.com/ErikKalkoken/evebuddy/internal/set"
)

// Settings ...
type Settings interface {
	DeveloperMode() bool
	ResetDeveloperMode()
	SetDeveloperMode(v bool)
	LogLevel() string
	LogLevelDefault() string
	ResetLogLevel()
	SetLogLevel(l string)
	MaxMails() int
	MaxMailsPresets() (min int, max int, def int)
	ResetMaxMails()
	SetMaxMails(v int)
	SysTrayEnabled() bool
	ResetSysTrayEnabled()
	SetSysTrayEnabled(v bool)
	WindowSize() fyne.Size
	ResetWindowSize()
	SetWindowSize(v fyne.Size)
	TabsMainID() int
	ResetTabsMainID()
	SetTabsMainID(v int)
	LastCharacterID() int32
	ResetLastCharacterID()
	SetLastCharacterID(id int32)
	MaxWalletTransactions() int
	MaxWalletTransactionsPresets() (min int, max int, def int)
	ResetMaxWalletTransactions()
	SetMaxWalletTransactions(v int)
	NotifyTimeoutHours() int
	NotifyTimeoutHoursPresets() (min int, max int, def int)
	ResetNotifyTimeoutHours()
	SetNotifyTimeoutHours(v int)
	NotificationTypesEnabled() set.Set[string]
	ResetNotificationTypesEnabled()
	SetNotificationTypesEnabled(v set.Set[string])
	NotifyCommunicationsEarliest() time.Time
	SetNotifyCommunicationsEarliest(t time.Time)
	NotifyContractsEarliest() time.Time
	SetNotifyContractsEarliest(t time.Time)
	NotifyMailsEarliest() time.Time
	SetNotifyMailsEarliest(t time.Time)
	NotifyPIEarliest() time.Time
	SetNotifyPIEarliest(t time.Time)
	NotifyTrainingEarliest() time.Time
	SetNotifyTrainingEarliest(t time.Time)
	NotifyCommunicationsEnabled() bool
	ResetNotifyCommunicationsEnabled()
	SetNotifyCommunicationsEnabled(v bool)
	NotifyContractsEnabled() bool
	ResetNotifyContractsEnabled()
	SetNotifyContractsEnabled(v bool)
	NotifyMailsEnabled() bool
	ResetNotifyMailsEnabled()
	SetNotifyMailsEnabled(v bool)
	NotifyPIEnabled() bool
	ResetNotifyPIEnabled()
	SetNotifyPIEnabled(v bool)
	NotifyTrainingEnabled() bool
	ResetNotifyTrainingEnabled()
	SetNotifyTrainingEnabled(v bool)
}
