// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package icons

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed access_time.svg
var AccesstimeSvgData []byte
var AccesstimeSvg = &fyne.StaticResource{
	StaticName:    "access_time.svg",
	StaticContent: AccesstimeSvgData,
}

//go:embed access_time_filled.svg
var AccesstimefilledSvgData []byte
var AccesstimefilledSvg = &fyne.StaticResource{
	StaticName:    "access_time_filled.svg",
	StaticContent: AccesstimefilledSvgData,
}

//go:embed account-circle.svg
var AccountCircleSvgData []byte
var AccountCircleSvg = &fyne.StaticResource{
	StaticName:    "account-circle.svg",
	StaticContent: AccountCircleSvgData,
}

//go:embed account-multiple-outline.svg
var AccountMultipleOutlineSvgData []byte
var AccountMultipleOutlineSvg = &fyne.StaticResource{
	StaticName:    "account-multiple-outline.svg",
	StaticContent: AccountMultipleOutlineSvgData,
}

//go:embed account-multiple.svg
var AccountMultipleSvgData []byte
var AccountMultipleSvg = &fyne.StaticResource{
	StaticName:    "account-multiple.svg",
	StaticContent: AccountMultipleSvgData,
}

//go:embed account-outline.svg
var AccountOutlineSvgData []byte
var AccountOutlineSvg = &fyne.StaticResource{
	StaticName:    "account-outline.svg",
	StaticContent: AccountOutlineSvgData,
}

//go:embed account.svg
var AccountSvgData []byte
var AccountSvg = &fyne.StaticResource{
	StaticName:    "account.svg",
	StaticContent: AccountSvgData,
}

//go:embed arrow-collapse-vertical.svg
var ArrowCollapseVerticalSvgData []byte
var ArrowCollapseVerticalSvg = &fyne.StaticResource{
	StaticName:    "arrow-collapse-vertical.svg",
	StaticContent: ArrowCollapseVerticalSvgData,
}

//go:embed arrow-left.svg
var ArrowLeftSvgData []byte
var ArrowLeftSvg = &fyne.StaticResource{
	StaticName:    "arrow-left.svg",
	StaticContent: ArrowLeftSvgData,
}

//go:embed arrow-right.svg
var ArrowRightSvgData []byte
var ArrowRightSvg = &fyne.StaticResource{
	StaticName:    "arrow-right.svg",
	StaticContent: ArrowRightSvgData,
}

//go:embed attach_money.svg
var AttachmoneySvgData []byte
var AttachmoneySvg = &fyne.StaticResource{
	StaticName:    "attach_money.svg",
	StaticContent: AttachmoneySvgData,
}

//go:embed blank.svg
var BlankSvgData []byte
var BlankSvg = &fyne.StaticResource{
	StaticName:    "blank.svg",
	StaticContent: BlankSvgData,
}

//go:embed bug.svg
var BugSvgData []byte
var BugSvg = &fyne.StaticResource{
	StaticName:    "bug.svg",
	StaticContent: BugSvgData,
}

//go:embed cash.svg
var CashSvgData []byte
var CashSvg = &fyne.StaticResource{
	StaticName:    "cash.svg",
	StaticContent: CashSvgData,
}

//go:embed character_placeholder_128.jpeg
var Characterplaceholder128JpegData []byte
var Characterplaceholder128Jpeg = &fyne.StaticResource{
	StaticName:    "character_placeholder_128.jpeg",
	StaticContent: Characterplaceholder128JpegData,
}

//go:embed character_placeholder_256.jpeg
var Characterplaceholder256JpegData []byte
var Characterplaceholder256Jpeg = &fyne.StaticResource{
	StaticName:    "character_placeholder_256.jpeg",
	StaticContent: Characterplaceholder256JpegData,
}

//go:embed character_placeholder_32.jpeg
var Characterplaceholder32JpegData []byte
var Characterplaceholder32Jpeg = &fyne.StaticResource{
	StaticName:    "character_placeholder_32.jpeg",
	StaticContent: Characterplaceholder32JpegData,
}

//go:embed character_placeholder_512.jpeg
var Characterplaceholder512JpegData []byte
var Characterplaceholder512Jpeg = &fyne.StaticResource{
	StaticName:    "character_placeholder_512.jpeg",
	StaticContent: Characterplaceholder512JpegData,
}

//go:embed character_placeholder_64.jpeg
var Characterplaceholder64JpegData []byte
var Characterplaceholder64Jpeg = &fyne.StaticResource{
	StaticName:    "character_placeholder_64.jpeg",
	StaticContent: Characterplaceholder64JpegData,
}

//go:embed chart-areaspline.svg
var ChartAreasplineSvgData []byte
var ChartAreasplineSvg = &fyne.StaticResource{
	StaticName:    "chart-areaspline.svg",
	StaticContent: ChartAreasplineSvgData,
}

//go:embed chart-bar.svg
var ChartBarSvgData []byte
var ChartBarSvg = &fyne.StaticResource{
	StaticName:    "chart-bar.svg",
	StaticContent: ChartBarSvgData,
}

//go:embed check-decagram.svg
var CheckDecagramSvgData []byte
var CheckDecagramSvg = &fyne.StaticResource{
	StaticName:    "check-decagram.svg",
	StaticContent: CheckDecagramSvgData,
}

//go:embed checklist_rtl.svg
var ChecklistrtlSvgData []byte
var ChecklistrtlSvg = &fyne.StaticResource{
	StaticName:    "checklist_rtl.svg",
	StaticContent: ChecklistrtlSvgData,
}

//go:embed cog-outline.svg
var CogOutlineSvgData []byte
var CogOutlineSvg = &fyne.StaticResource{
	StaticName:    "cog-outline.svg",
	StaticContent: CogOutlineSvgData,
}

//go:embed cog.svg
var CogSvgData []byte
var CogSvg = &fyne.StaticResource{
	StaticName:    "cog.svg",
	StaticContent: CogSvgData,
}

//go:embed collapse-all-outline.svg
var CollapseAllOutlineSvgData []byte
var CollapseAllOutlineSvg = &fyne.StaticResource{
	StaticName:    "collapse-all-outline.svg",
	StaticContent: CollapseAllOutlineSvgData,
}

//go:embed collapse-all.svg
var CollapseAllSvgData []byte
var CollapseAllSvg = &fyne.StaticResource{
	StaticName:    "collapse-all.svg",
	StaticContent: CollapseAllSvgData,
}

//go:embed constellation_64.png
var Constellation64PngData []byte
var Constellation64Png = &fyne.StaticResource{
	StaticName:    "constellation_64.png",
	StaticContent: Constellation64PngData,
}

//go:embed corporation_placeholder_64.png
var Corporationplaceholder64PngData []byte
var Corporationplaceholder64Png = &fyne.StaticResource{
	StaticName:    "corporation_placeholder_64.png",
	StaticContent: Corporationplaceholder64PngData,
}

//go:embed crown.svg
var CrownSvgData []byte
var CrownSvg = &fyne.StaticResource{
	StaticName:    "crown.svg",
	StaticContent: CrownSvgData,
}

//go:embed dotlan-avatar.png
var DotlanAvatarPngData []byte
var DotlanAvatarPng = &fyne.StaticResource{
	StaticName:    "dotlan-avatar.png",
	StaticContent: DotlanAvatarPngData,
}

//go:embed earth.svg
var EarthSvgData []byte
var EarthSvg = &fyne.StaticResource{
	StaticName:    "earth.svg",
	StaticContent: EarthSvgData,
}

//go:embed evelogo.png
var EvelogoPngData []byte
var EvelogoPng = &fyne.StaticResource{
	StaticName:    "evelogo.png",
	StaticContent: EvelogoPngData,
}

//go:embed evemarketbrowser.jpg
var EvemarketbrowserJpgData []byte
var EvemarketbrowserJpg = &fyne.StaticResource{
	StaticName:    "evemarketbrowser.jpg",
	StaticContent: EvemarketbrowserJpgData,
}

//go:embed expand-all.svg
var ExpandAllSvgData []byte
var ExpandAllSvg = &fyne.StaticResource{
	StaticName:    "expand-all.svg",
	StaticContent: ExpandAllSvgData,
}

//go:embed faction_placeholder_64.png
var Factionplaceholder64PngData []byte
var Factionplaceholder64Png = &fyne.StaticResource{
	StaticName:    "faction_placeholder_64.png",
	StaticContent: Factionplaceholder64PngData,
}

//go:embed factory.svg
var FactorySvgData []byte
var FactorySvg = &fyne.StaticResource{
	StaticName:    "factory.svg",
	StaticContent: FactorySvgData,
}

//go:embed file-sign.svg
var FileSignSvgData []byte
var FileSignSvg = &fyne.StaticResource{
	StaticName:    "file-sign.svg",
	StaticContent: FileSignSvgData,
}

//go:embed gold.svg
var GoldSvgData []byte
var GoldSvg = &fyne.StaticResource{
	StaticName:    "gold.svg",
	StaticContent: GoldSvgData,
}

//go:embed group.svg
var GroupSvgData []byte
var GroupSvg = &fyne.StaticResource{
	StaticName:    "group.svg",
	StaticContent: GroupSvgData,
}

//go:embed head-snowflake.svg
var HeadSnowflakeSvgData []byte
var HeadSnowflakeSvg = &fyne.StaticResource{
	StaticName:    "head-snowflake.svg",
	StaticContent: HeadSnowflakeSvgData,
}

//go:embed help.svg
var HelpSvgData []byte
var HelpSvg = &fyne.StaticResource{
	StaticName:    "help.svg",
	StaticContent: HelpSvgData,
}

//go:embed icon.png
var IconPngData []byte
var IconPng = &fyne.StaticResource{
	StaticName:    "icon.png",
	StaticContent: IconPngData,
}

//go:embed icon_marked.png
var IconmarkedPngData []byte
var IconmarkedPng = &fyne.StaticResource{
	StaticName:    "icon_marked.png",
	StaticContent: IconmarkedPngData,
}

//go:embed indy_canceled.svg
var IndycanceledSvgData []byte
var IndycanceledSvg = &fyne.StaticResource{
	StaticName:    "indy_canceled.svg",
	StaticContent: IndycanceledSvgData,
}

//go:embed indy_copying.svg
var IndycopyingSvgData []byte
var IndycopyingSvg = &fyne.StaticResource{
	StaticName:    "indy_copying.svg",
	StaticContent: IndycopyingSvgData,
}

//go:embed indy_delivered.svg
var IndydeliveredSvgData []byte
var IndydeliveredSvg = &fyne.StaticResource{
	StaticName:    "indy_delivered.svg",
	StaticContent: IndydeliveredSvgData,
}

//go:embed indy_halted.svg
var IndyhaltedSvgData []byte
var IndyhaltedSvg = &fyne.StaticResource{
	StaticName:    "indy_halted.svg",
	StaticContent: IndyhaltedSvgData,
}

//go:embed indy_invention.svg
var IndyinventionSvgData []byte
var IndyinventionSvg = &fyne.StaticResource{
	StaticName:    "indy_invention.svg",
	StaticContent: IndyinventionSvgData,
}

//go:embed indy_manufacturing.svg
var IndymanufacturingSvgData []byte
var IndymanufacturingSvg = &fyne.StaticResource{
	StaticName:    "indy_manufacturing.svg",
	StaticContent: IndymanufacturingSvgData,
}

//go:embed indy_material_research.svg
var IndymaterialresearchSvgData []byte
var IndymaterialresearchSvg = &fyne.StaticResource{
	StaticName:    "indy_material_research.svg",
	StaticContent: IndymaterialresearchSvgData,
}

//go:embed indy_reactions.svg
var IndyreactionsSvgData []byte
var IndyreactionsSvg = &fyne.StaticResource{
	StaticName:    "indy_reactions.svg",
	StaticContent: IndyreactionsSvgData,
}

//go:embed indy_ready.svg
var IndyreadySvgData []byte
var IndyreadySvg = &fyne.StaticResource{
	StaticName:    "indy_ready.svg",
	StaticContent: IndyreadySvgData,
}

//go:embed indy_time_research.svg
var IndytimeresearchSvgData []byte
var IndytimeresearchSvg = &fyne.StaticResource{
	StaticName:    "indy_time_research.svg",
	StaticContent: IndytimeresearchSvgData,
}

//go:embed information-slab-circle.svg
var InformationSlabCircleSvgData []byte
var InformationSlabCircleSvg = &fyne.StaticResource{
	StaticName:    "information-slab-circle.svg",
	StaticContent: InformationSlabCircleSvgData,
}

//go:embed information.svg
var InformationSvgData []byte
var InformationSvg = &fyne.StaticResource{
	StaticName:    "information.svg",
	StaticContent: InformationSvgData,
}

//go:embed insights.svg
var InsightsSvgData []byte
var InsightsSvg = &fyne.StaticResource{
	StaticName:    "insights.svg",
	StaticContent: InsightsSvgData,
}

//go:embed inventory_2.svg
var Inventory2SvgData []byte
var Inventory2Svg = &fyne.StaticResource{
	StaticName:    "inventory_2.svg",
	StaticContent: Inventory2SvgData,
}

//go:embed janice.png
var JanicePngData []byte
var JanicePng = &fyne.StaticResource{
	StaticName:    "janice.png",
	StaticContent: JanicePngData,
}

//go:embed manage_accounts.svg
var ManageaccountsSvgData []byte
var ManageaccountsSvg = &fyne.StaticResource{
	StaticName:    "manage_accounts.svg",
	StaticContent: ManageaccountsSvgData,
}

//go:embed map-marker.svg
var MapMarkerSvgData []byte
var MapMarkerSvg = &fyne.StaticResource{
	StaticName:    "map-marker.svg",
	StaticContent: MapMarkerSvgData,
}

//go:embed message-outline.svg
var MessageOutlineSvgData []byte
var MessageOutlineSvg = &fyne.StaticResource{
	StaticName:    "message-outline.svg",
	StaticContent: MessageOutlineSvgData,
}

//go:embed message.svg
var MessageSvgData []byte
var MessageSvg = &fyne.StaticResource{
	StaticName:    "message.svg",
	StaticContent: MessageSvgData,
}

//go:embed numeric-1-circle.svg
var Numeric1CircleSvgData []byte
var Numeric1CircleSvg = &fyne.StaticResource{
	StaticName:    "numeric-1-circle.svg",
	StaticContent: Numeric1CircleSvgData,
}

//go:embed office-building.svg
var OfficeBuildingSvgData []byte
var OfficeBuildingSvg = &fyne.StaticResource{
	StaticName:    "office-building.svg",
	StaticContent: OfficeBuildingSvgData,
}

//go:embed portrait.svg
var PortraitSvgData []byte
var PortraitSvg = &fyne.StaticResource{
	StaticName:    "portrait.svg",
	StaticContent: PortraitSvgData,
}

//go:embed question_mark.svg
var QuestionmarkSvgData []byte
var QuestionmarkSvg = &fyne.StaticResource{
	StaticName:    "question_mark.svg",
	StaticContent: QuestionmarkSvgData,
}

//go:embed question_mark_32.png
var Questionmark32PngData []byte
var Questionmark32Png = &fyne.StaticResource{
	StaticName:    "question_mark_32.png",
	StaticContent: Questionmark32PngData,
}

//go:embed question_mark_small.svg
var QuestionmarksmallSvgData []byte
var QuestionmarksmallSvg = &fyne.StaticResource{
	StaticName:    "question_mark_small.svg",
	StaticContent: QuestionmarksmallSvgData,
}

//go:embed region_64.png
var Region64PngData []byte
var Region64Png = &fyne.StaticResource{
	StaticName:    "region_64.png",
	StaticContent: Region64PngData,
}

//go:embed school.svg
var SchoolSvgData []byte
var SchoolSvg = &fyne.StaticResource{
	StaticName:    "school.svg",
	StaticContent: SchoolSvgData,
}

//go:embed script-text.svg
var ScriptTextSvgData []byte
var ScriptTextSvg = &fyne.StaticResource{
	StaticName:    "script-text.svg",
	StaticContent: ScriptTextSvgData,
}

//go:embed ship-wheel.svg
var ShipWheelSvgData []byte
var ShipWheelSvg = &fyne.StaticResource{
	StaticName:    "ship-wheel.svg",
	StaticContent: ShipWheelSvgData,
}

//go:embed sort-ascending.svg
var SortAscendingSvgData []byte
var SortAscendingSvg = &fyne.StaticResource{
	StaticName:    "sort-ascending.svg",
	StaticContent: SortAscendingSvgData,
}

//go:embed sort-descending.svg
var SortDescendingSvgData []byte
var SortDescendingSvg = &fyne.StaticResource{
	StaticName:    "sort-descending.svg",
	StaticContent: SortDescendingSvgData,
}

//go:embed sort.svg
var SortSvgData []byte
var SortSvg = &fyne.StaticResource{
	StaticName:    "sort.svg",
	StaticContent: SortSvgData,
}

//go:embed space-station.svg
var SpaceStationSvgData []byte
var SpaceStationSvg = &fyne.StaticResource{
	StaticName:    "space-station.svg",
	StaticContent: SpaceStationSvgData,
}

//go:embed star-circle-outline.svg
var StarCircleOutlineSvgData []byte
var StarCircleOutlineSvg = &fyne.StaticResource{
	StaticName:    "star-circle-outline.svg",
	StaticContent: StarCircleOutlineSvgData,
}

//go:embed switch_account.svg
var SwitchaccountSvgData []byte
var SwitchaccountSvg = &fyne.StaticResource{
	StaticName:    "switch_account.svg",
	StaticContent: SwitchaccountSvgData,
}

//go:embed teddy-bear.svg
var TeddyBearSvgData []byte
var TeddyBearSvg = &fyne.StaticResource{
	StaticName:    "teddy-bear.svg",
	StaticContent: TeddyBearSvgData,
}

//go:embed tools.svg
var ToolsSvgData []byte
var ToolsSvg = &fyne.StaticResource{
	StaticName:    "tools.svg",
	StaticContent: ToolsSvgData,
}

//go:embed tune-variant.svg
var TuneVariantSvgData []byte
var TuneVariantSvg = &fyne.StaticResource{
	StaticName:    "tune-variant.svg",
	StaticContent: TuneVariantSvgData,
}

//go:embed tune.svg
var TuneSvgData []byte
var TuneSvg = &fyne.StaticResource{
	StaticName:    "tune.svg",
	StaticContent: TuneSvgData,
}

//go:embed type_placeholder_64.png
var Typeplaceholder64PngData []byte
var Typeplaceholder64Png = &fyne.StaticResource{
	StaticName:    "type_placeholder_64.png",
	StaticContent: Typeplaceholder64PngData,
}

//go:embed update.svg
var UpdateSvgData []byte
var UpdateSvg = &fyne.StaticResource{
	StaticName:    "update.svg",
	StaticContent: UpdateSvgData,
}

//go:embed wrench-cog-outline.svg
var WrenchCogOutlineSvgData []byte
var WrenchCogOutlineSvg = &fyne.StaticResource{
	StaticName:    "wrench-cog-outline.svg",
	StaticContent: WrenchCogOutlineSvgData,
}

//go:embed wrench-cog.svg
var WrenchCogSvgData []byte
var WrenchCogSvg = &fyne.StaticResource{
	StaticName:    "wrench-cog.svg",
	StaticContent: WrenchCogSvgData,
}

//go:embed zkillboard.png
var ZkillboardPngData []byte
var ZkillboardPng = &fyne.StaticResource{
	StaticName:    "zkillboard.png",
	StaticContent: ZkillboardPngData,
}
