// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type Character struct {
	AllianceID     sql.NullInt64
	Birthday       time.Time
	CorporationID  int64
	Description    string
	Gender         string
	FactionID      sql.NullInt64
	ID             int64
	LastLoginAt    time.Time
	MailUpdatedAt  sql.NullTime
	Name           string
	RaceID         int64
	SecurityStatus float64
	SkillPoints    int64
	LocationID     int64
	WalletBalance  float64
}

type Dictionary struct {
	Key   string
	Value []byte
}

type EveEntity struct {
	ID       int64
	Category string
	Name     string
}

type Mail struct {
	ID          int64
	Body        string
	CharacterID int64
	FromID      int64
	IsRead      bool
	MailID      int64
	Subject     string
	Timestamp   time.Time
}

type MailLabel struct {
	ID          int64
	CharacterID int64
	Color       string
	LabelID     int64
	Name        string
	UnreadCount int64
}

type MailList struct {
	CharacterID int64
	EveEntityID int64
}

type MailMailLabel struct {
	MailLabelID int64
	MailID      int64
}

type MailRecipient struct {
	MailID      int64
	EveEntityID int64
}

type Race struct {
	ID          int64
	Description string
	Name        string
}

type Token struct {
	AccessToken  string
	CharacterID  int64
	ExpiresAt    time.Time
	RefreshToken string
	TokenType    string
}
