// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: character_notifications.sql

package queries

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const calcCharacterNotificationUnreadCounts = `-- name: CalcCharacterNotificationUnreadCounts :many
SELECT cn.type_id, nt.name, SUM(NOT cn.is_read)
FROM character_notifications cn
JOIN notification_types nt ON nt.id = cn.type_id
WHERE character_id = ?
GROUP BY cn.type_id, nt.name
`

type CalcCharacterNotificationUnreadCountsRow struct {
	TypeID int64
	Name   string
	Sum    sql.NullFloat64
}

func (q *Queries) CalcCharacterNotificationUnreadCounts(ctx context.Context, characterID int64) ([]CalcCharacterNotificationUnreadCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, calcCharacterNotificationUnreadCounts, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalcCharacterNotificationUnreadCountsRow
	for rows.Next() {
		var i CalcCharacterNotificationUnreadCountsRow
		if err := rows.Scan(&i.TypeID, &i.Name, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCharacterNotification = `-- name: CreateCharacterNotification :exec
INSERT INTO character_notifications (
    character_id,
    is_read,
    notification_id,
    sender_id,
    text,
    timestamp,
    type_id
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCharacterNotificationParams struct {
	CharacterID    int64
	IsRead         bool
	NotificationID int64
	SenderID       int64
	Text           string
	Timestamp      time.Time
	TypeID         int64
}

func (q *Queries) CreateCharacterNotification(ctx context.Context, arg CreateCharacterNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createCharacterNotification,
		arg.CharacterID,
		arg.IsRead,
		arg.NotificationID,
		arg.SenderID,
		arg.Text,
		arg.Timestamp,
		arg.TypeID,
	)
	return err
}

const createNotificationType = `-- name: CreateNotificationType :one
INSERT INTO notification_types (
    name
)
VALUES (
    ?
)
RETURNING id
`

func (q *Queries) CreateNotificationType(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createNotificationType, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCharacterNotification = `-- name: GetCharacterNotification :one
SELECT cn.id, cn.character_id, cn.is_read, cn.notification_id, cn.sender_id, cn.text, cn.timestamp, cn.type_id, ee.id, ee.category, ee.name, nt.id, nt.name
FROM character_notifications cn
JOIN eve_entities ee ON ee.id = cn.sender_id
JOIN notification_types nt ON nt.id = cn.type_id
WHERE character_id = ? and notification_id = ?
`

type GetCharacterNotificationParams struct {
	CharacterID    int64
	NotificationID int64
}

type GetCharacterNotificationRow struct {
	CharacterNotification CharacterNotification
	EveEntity             EveEntity
	NotificationType      NotificationType
}

func (q *Queries) GetCharacterNotification(ctx context.Context, arg GetCharacterNotificationParams) (GetCharacterNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, getCharacterNotification, arg.CharacterID, arg.NotificationID)
	var i GetCharacterNotificationRow
	err := row.Scan(
		&i.CharacterNotification.ID,
		&i.CharacterNotification.CharacterID,
		&i.CharacterNotification.IsRead,
		&i.CharacterNotification.NotificationID,
		&i.CharacterNotification.SenderID,
		&i.CharacterNotification.Text,
		&i.CharacterNotification.Timestamp,
		&i.CharacterNotification.TypeID,
		&i.EveEntity.ID,
		&i.EveEntity.Category,
		&i.EveEntity.Name,
		&i.NotificationType.ID,
		&i.NotificationType.Name,
	)
	return i, err
}

const getNotificationTypeID = `-- name: GetNotificationTypeID :one
SELECT id
FROM notification_types
WHERE name = ?
`

func (q *Queries) GetNotificationTypeID(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNotificationTypeID, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCharacterNotificationIDs = `-- name: ListCharacterNotificationIDs :many
SELECT notification_id
FROM character_notifications
WHERE character_id = ?
`

func (q *Queries) ListCharacterNotificationIDs(ctx context.Context, characterID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterNotificationIDs, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var notification_id int64
		if err := rows.Scan(&notification_id); err != nil {
			return nil, err
		}
		items = append(items, notification_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterNotificationsTypes = `-- name: ListCharacterNotificationsTypes :many
SELECT cn.id, cn.character_id, cn.is_read, cn.notification_id, cn.sender_id, cn.text, cn.timestamp, cn.type_id, ee.id, ee.category, ee.name, nt.id, nt.name
FROM character_notifications cn
JOIN eve_entities ee ON ee.id = cn.sender_id
JOIN notification_types nt ON nt.id = cn.type_id
WHERE character_id = ?
AND nt.name IN (/*SLICE:names*/?)
ORDER BY timestamp DESC
`

type ListCharacterNotificationsTypesParams struct {
	CharacterID int64
	Names       []string
}

type ListCharacterNotificationsTypesRow struct {
	CharacterNotification CharacterNotification
	EveEntity             EveEntity
	NotificationType      NotificationType
}

func (q *Queries) ListCharacterNotificationsTypes(ctx context.Context, arg ListCharacterNotificationsTypesParams) ([]ListCharacterNotificationsTypesRow, error) {
	query := listCharacterNotificationsTypes
	var queryParams []interface{}
	queryParams = append(queryParams, arg.CharacterID)
	if len(arg.Names) > 0 {
		for _, v := range arg.Names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(arg.Names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterNotificationsTypesRow
	for rows.Next() {
		var i ListCharacterNotificationsTypesRow
		if err := rows.Scan(
			&i.CharacterNotification.ID,
			&i.CharacterNotification.CharacterID,
			&i.CharacterNotification.IsRead,
			&i.CharacterNotification.NotificationID,
			&i.CharacterNotification.SenderID,
			&i.CharacterNotification.Text,
			&i.CharacterNotification.Timestamp,
			&i.CharacterNotification.TypeID,
			&i.EveEntity.ID,
			&i.EveEntity.Category,
			&i.EveEntity.Name,
			&i.NotificationType.ID,
			&i.NotificationType.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterNotificationsUnread = `-- name: ListCharacterNotificationsUnread :many
SELECT cn.id, cn.character_id, cn.is_read, cn.notification_id, cn.sender_id, cn.text, cn.timestamp, cn.type_id, ee.id, ee.category, ee.name, nt.id, nt.name
FROM character_notifications cn
JOIN eve_entities ee ON ee.id = cn.sender_id
JOIN notification_types nt ON nt.id = cn.type_id
WHERE character_id = ?
AND cn.is_read IS FALSE
ORDER BY timestamp DESC
`

type ListCharacterNotificationsUnreadRow struct {
	CharacterNotification CharacterNotification
	EveEntity             EveEntity
	NotificationType      NotificationType
}

func (q *Queries) ListCharacterNotificationsUnread(ctx context.Context, characterID int64) ([]ListCharacterNotificationsUnreadRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacterNotificationsUnread, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharacterNotificationsUnreadRow
	for rows.Next() {
		var i ListCharacterNotificationsUnreadRow
		if err := rows.Scan(
			&i.CharacterNotification.ID,
			&i.CharacterNotification.CharacterID,
			&i.CharacterNotification.IsRead,
			&i.CharacterNotification.NotificationID,
			&i.CharacterNotification.SenderID,
			&i.CharacterNotification.Text,
			&i.CharacterNotification.Timestamp,
			&i.CharacterNotification.TypeID,
			&i.EveEntity.ID,
			&i.EveEntity.Category,
			&i.EveEntity.Name,
			&i.NotificationType.ID,
			&i.NotificationType.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterNotificationsIsRead = `-- name: UpdateCharacterNotificationsIsRead :exec
UPDATE character_notifications
SET is_read = ?2
WHERE id = ?1
`

type UpdateCharacterNotificationsIsReadParams struct {
	ID     int64
	IsRead bool
}

func (q *Queries) UpdateCharacterNotificationsIsRead(ctx context.Context, arg UpdateCharacterNotificationsIsReadParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterNotificationsIsRead, arg.ID, arg.IsRead)
	return err
}
