// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: eve_races.sql

package queries

import (
	"context"
	"database/sql"
)

const createEveRace = `-- name: CreateEveRace :exec
INSERT INTO
    eve_races (id, description, name, faction_id)
VALUES
    (?, ?, ?, ?)
`

type CreateEveRaceParams struct {
	ID          int64
	Description string
	Name        string
	FactionID   sql.NullInt64
}

func (q *Queries) CreateEveRace(ctx context.Context, arg CreateEveRaceParams) error {
	_, err := q.db.ExecContext(ctx, createEveRace,
		arg.ID,
		arg.Description,
		arg.Name,
		arg.FactionID,
	)
	return err
}

const getEveRace = `-- name: GetEveRace :one
SELECT
    er.id, er.description, er.name, er.faction_id,
    ee.name as alliance_name
FROM
    eve_races er
    LEFT JOIN eve_entities ee ON ee.id = er.faction_id
WHERE
    er.id = ?
`

type GetEveRaceRow struct {
	EveRace      EveRace
	AllianceName sql.NullString
}

func (q *Queries) GetEveRace(ctx context.Context, id int64) (GetEveRaceRow, error) {
	row := q.db.QueryRowContext(ctx, getEveRace, id)
	var i GetEveRaceRow
	err := row.Scan(
		&i.EveRace.ID,
		&i.EveRace.Description,
		&i.EveRace.Name,
		&i.EveRace.FactionID,
		&i.AllianceName,
	)
	return i, err
}

const listEveRaceIDs = `-- name: ListEveRaceIDs :many
SELECT
    id
FROM
    eve_races
`

func (q *Queries) ListEveRaceIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEveRaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
