// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: eve_factions.sql

package queries

import (
	"context"
	"database/sql"
)

const createEveFaction = `-- name: CreateEveFaction :exec
INSERT INTO
    eve_factions (
        id,
        corporation_id,
        description,
        is_unique,
        militia_corporation_id,
        name,
        size_factor,
        solar_system_id,
        station_count,
        station_system_count
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEveFactionParams struct {
	ID                   int64
	CorporationID        sql.NullInt64
	Description          string
	IsUnique             bool
	MilitiaCorporationID sql.NullInt64
	Name                 string
	SizeFactor           float64
	SolarSystemID        sql.NullInt64
	StationCount         int64
	StationSystemCount   int64
}

func (q *Queries) CreateEveFaction(ctx context.Context, arg CreateEveFactionParams) error {
	_, err := q.db.ExecContext(ctx, createEveFaction,
		arg.ID,
		arg.CorporationID,
		arg.Description,
		arg.IsUnique,
		arg.MilitiaCorporationID,
		arg.Name,
		arg.SizeFactor,
		arg.SolarSystemID,
		arg.StationCount,
		arg.StationSystemCount,
	)
	return err
}

const getEveFaction = `-- name: GetEveFaction :one
SELECT
    ef.id, ef.corporation_id, ef.description, ef.is_unique, ef.militia_corporation_id, ef.name, ef.size_factor, ef.solar_system_id, ef.station_count, ef.station_system_count,
    eec.name as corporation_name,
    eem.name as militia_corporation_name,
    ees.name as solar_system_name
FROM
    eve_factions ef
    LEFT JOIN eve_entities eec ON eec.id = ef.corporation_id
    LEFT JOIN eve_entities eem ON eem.id = ef.militia_corporation_id
    LEFT JOIN eve_solar_systems ees ON ees.id = ef.solar_system_id
WHERE
    ef.id = ?
`

type GetEveFactionRow struct {
	EveFaction             EveFaction
	CorporationName        sql.NullString
	MilitiaCorporationName sql.NullString
	SolarSystemName        sql.NullString
}

func (q *Queries) GetEveFaction(ctx context.Context, id int64) (GetEveFactionRow, error) {
	row := q.db.QueryRowContext(ctx, getEveFaction, id)
	var i GetEveFactionRow
	err := row.Scan(
		&i.EveFaction.ID,
		&i.EveFaction.CorporationID,
		&i.EveFaction.Description,
		&i.EveFaction.IsUnique,
		&i.EveFaction.MilitiaCorporationID,
		&i.EveFaction.Name,
		&i.EveFaction.SizeFactor,
		&i.EveFaction.SolarSystemID,
		&i.EveFaction.StationCount,
		&i.EveFaction.StationSystemCount,
		&i.CorporationName,
		&i.MilitiaCorporationName,
		&i.SolarSystemName,
	)
	return i, err
}

const listEveFactionIDs = `-- name: ListEveFactionIDs :many
SELECT
    id
FROM
    eve_factions
`

func (q *Queries) ListEveFactionIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEveFactionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
