// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: eve_bloodlines.sql

package queries

import (
	"context"
	"database/sql"
)

const createEveBloodline = `-- name: CreateEveBloodline :exec
INSERT INTO
    eve_bloodlines (
        id,
        charisma,
        corporation_id,
        description,
        intelligence,
        memory,
        name,
        perception,
        race_id,
        ship_type_id,
        willpower
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEveBloodlineParams struct {
	ID            int64
	Charisma      sql.NullInt64
	CorporationID int64
	Description   string
	Intelligence  sql.NullInt64
	Memory        sql.NullInt64
	Name          string
	Perception    sql.NullInt64
	RaceID        int64
	ShipTypeID    sql.NullInt64
	Willpower     sql.NullInt64
}

func (q *Queries) CreateEveBloodline(ctx context.Context, arg CreateEveBloodlineParams) error {
	_, err := q.db.ExecContext(ctx, createEveBloodline,
		arg.ID,
		arg.Charisma,
		arg.CorporationID,
		arg.Description,
		arg.Intelligence,
		arg.Memory,
		arg.Name,
		arg.Perception,
		arg.RaceID,
		arg.ShipTypeID,
		arg.Willpower,
	)
	return err
}

const getEveBloodline = `-- name: GetEveBloodline :one
SELECT
    eb.id, eb.charisma, eb.corporation_id, eb.description, eb.intelligence, eb.memory, eb.name, eb.perception, eb.race_id, eb.ship_type_id, eb.willpower,
    eec.id, eec.category, eec.name,
    er.id, er.description, er.name, er.faction_id,
    eea.name as faction_name
FROM
    eve_bloodlines eb
    JOIN eve_entities eec ON eec.id = eb.corporation_id
    JOIN eve_races er ON er.id = eb.race_id
    LEFT JOIN eve_entities eea ON eea.id = er.faction_id
WHERE
    eb.id = ?
`

type GetEveBloodlineRow struct {
	EveBloodline EveBloodline
	EveEntity    EveEntity
	EveRace      EveRace
	FactionName  sql.NullString
}

func (q *Queries) GetEveBloodline(ctx context.Context, id int64) (GetEveBloodlineRow, error) {
	row := q.db.QueryRowContext(ctx, getEveBloodline, id)
	var i GetEveBloodlineRow
	err := row.Scan(
		&i.EveBloodline.ID,
		&i.EveBloodline.Charisma,
		&i.EveBloodline.CorporationID,
		&i.EveBloodline.Description,
		&i.EveBloodline.Intelligence,
		&i.EveBloodline.Memory,
		&i.EveBloodline.Name,
		&i.EveBloodline.Perception,
		&i.EveBloodline.RaceID,
		&i.EveBloodline.ShipTypeID,
		&i.EveBloodline.Willpower,
		&i.EveEntity.ID,
		&i.EveEntity.Category,
		&i.EveEntity.Name,
		&i.EveRace.ID,
		&i.EveRace.Description,
		&i.EveRace.Name,
		&i.EveRace.FactionID,
		&i.FactionName,
	)
	return i, err
}

const listEveBloodlineIDs = `-- name: ListEveBloodlineIDs :many
SELECT
    id
FROM
    eve_bloodlines
`

func (q *Queries) ListEveBloodlineIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEveBloodlineIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
