// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: eve_characters.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const deleteEveCharacter = `-- name: DeleteEveCharacter :exec
DELETE FROM eve_characters
WHERE
    id = ?
`

func (q *Queries) DeleteEveCharacter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEveCharacter, id)
	return err
}

const getEveCharacter = `-- name: GetEveCharacter :one
SELECT
    ec.alliance_id, ec.birthday, ec.corporation_id, ec.description, ec.gender, ec.faction_id, ec.id, ec.name, ec.race_id, ec.security_status, ec.title, ec.bloodline_id,
    eec.id, eec.category, eec.name,
    er.id, er.description, er.name, er.faction_id,
    eea.name as alliance_name,
    eea.category as alliance_category,
    eef.name as faction_name,
    eef.category as faction_category,
    eb.id as bloodline_id,
    eb.name as bloodline_name,
    eer.name as race_faction_name
FROM
    eve_characters ec
    JOIN eve_entities eec ON eec.id = ec.corporation_id
    JOIN eve_races er ON er.id = ec.race_id
    LEFT JOIN eve_entities eea ON eea.id = ec.alliance_id
    LEFT JOIN eve_entities eef ON eef.id = ec.faction_id
    LEFT JOIN eve_bloodlines eb ON eb.id = ec.bloodline_id
    LEFT JOIN eve_entities eer ON eer.id = er.faction_id
WHERE
    ec.id = ?
`

type GetEveCharacterRow struct {
	EveCharacter     EveCharacter
	EveEntity        EveEntity
	EveRace          EveRace
	AllianceName     sql.NullString
	AllianceCategory sql.NullString
	FactionName      sql.NullString
	FactionCategory  sql.NullString
	BloodlineID      sql.NullInt64
	BloodlineName    sql.NullString
	RaceFactionName  sql.NullString
}

func (q *Queries) GetEveCharacter(ctx context.Context, id int64) (GetEveCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, getEveCharacter, id)
	var i GetEveCharacterRow
	err := row.Scan(
		&i.EveCharacter.AllianceID,
		&i.EveCharacter.Birthday,
		&i.EveCharacter.CorporationID,
		&i.EveCharacter.Description,
		&i.EveCharacter.Gender,
		&i.EveCharacter.FactionID,
		&i.EveCharacter.ID,
		&i.EveCharacter.Name,
		&i.EveCharacter.RaceID,
		&i.EveCharacter.SecurityStatus,
		&i.EveCharacter.Title,
		&i.EveCharacter.BloodlineID,
		&i.EveEntity.ID,
		&i.EveEntity.Category,
		&i.EveEntity.Name,
		&i.EveRace.ID,
		&i.EveRace.Description,
		&i.EveRace.Name,
		&i.EveRace.FactionID,
		&i.AllianceName,
		&i.AllianceCategory,
		&i.FactionName,
		&i.FactionCategory,
		&i.BloodlineID,
		&i.BloodlineName,
		&i.RaceFactionName,
	)
	return i, err
}

const listEveCharacterIDs = `-- name: ListEveCharacterIDs :many
SELECT
    id
FROM
    eve_characters
`

func (q *Queries) ListEveCharacterIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listEveCharacterIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEveCharacterName = `-- name: UpdateEveCharacterName :exec
UPDATE eve_characters
SET
    name = ?
WHERE
    id = ?
`

type UpdateEveCharacterNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateEveCharacterName(ctx context.Context, arg UpdateEveCharacterNameParams) error {
	_, err := q.db.ExecContext(ctx, updateEveCharacterName, arg.Name, arg.ID)
	return err
}

const updateOrCreateEveCharacter = `-- name: UpdateOrCreateEveCharacter :exec
INSERT INTO
    eve_characters (
        id,
        alliance_id,
        birthday,
        bloodline_id,
        corporation_id,
        description,
        faction_id,
        gender,
        name,
        race_id,
        security_status,
        title
    )
VALUES
    (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
ON CONFLICT (id) DO UPDATE
SET
    alliance_id = ?2,
    birthday = ?3,
    bloodline_id = ?4,
    corporation_id = ?5,
    description = ?6,
    faction_id = ?7,
    gender = ?8,
    name = ?9,
    race_id = ?10,
    security_status = ?11,
    title = ?12
`

type UpdateOrCreateEveCharacterParams struct {
	ID             int64
	AllianceID     sql.NullInt64
	Birthday       time.Time
	BloodlineID    sql.NullInt64
	CorporationID  int64
	Description    string
	FactionID      sql.NullInt64
	Gender         string
	Name           string
	RaceID         int64
	SecurityStatus float64
	Title          string
}

func (q *Queries) UpdateOrCreateEveCharacter(ctx context.Context, arg UpdateOrCreateEveCharacterParams) error {
	_, err := q.db.ExecContext(ctx, updateOrCreateEveCharacter,
		arg.ID,
		arg.AllianceID,
		arg.Birthday,
		arg.BloodlineID,
		arg.CorporationID,
		arg.Description,
		arg.FactionID,
		arg.Gender,
		arg.Name,
		arg.RaceID,
		arg.SecurityStatus,
		arg.Title,
	)
	return err
}
