// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
	"time"
)

type Character struct {
	ID            int64
	HomeID        sql.NullInt64
	LastLoginAt   sql.NullTime
	LocationID    sql.NullInt64
	ShipID        sql.NullInt64
	TotalSp       sql.NullInt64
	UnallocatedSp sql.NullInt64
	WalletBalance sql.NullFloat64
	AssetValue    sql.NullFloat64
}

type CharacterAsset struct {
	ID              int64
	CharacterID     int64
	EveTypeID       int64
	IsBlueprintCopy bool
	IsSingleton     bool
	ItemID          int64
	LocationFlag    string
	LocationID      int64
	LocationType    string
	Name            string
	Quantity        int64
}

type CharacterAttribute struct {
	ID            int64
	BonusRemaps   int64
	CharacterID   int64
	Charisma      int64
	Intelligence  int64
	LastRemapDate sql.NullTime
	Memory        int64
	Perception    int64
	Willpower     int64
}

type CharacterImplant struct {
	ID          int64
	CharacterID int64
	EveTypeID   int64
}

type CharacterJumpClone struct {
	ID          int64
	CharacterID int64
	JumpCloneID int64
	LocationID  int64
	Name        string
}

type CharacterJumpCloneImplant struct {
	ID        int64
	CloneID   int64
	EveTypeID int64
}

type CharacterMail struct {
	ID          int64
	Body        string
	CharacterID int64
	FromID      int64
	IsRead      bool
	MailID      int64
	Subject     string
	Timestamp   time.Time
}

type CharacterMailLabel struct {
	ID          int64
	CharacterID int64
	Color       string
	LabelID     int64
	Name        string
	UnreadCount int64
}

type CharacterMailList struct {
	ID          int64
	CharacterID int64
	EveEntityID int64
}

type CharacterMailMailLabel struct {
	ID                   int64
	CharacterMailLabelID int64
	CharacterMailID      int64
}

type CharacterMailsRecipient struct {
	ID          int64
	MailID      int64
	EveEntityID int64
}

type CharacterSectionStatus struct {
	ID          int64
	CharacterID int64
	SectionID   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ContentHash string
	CompletedAt sql.NullTime
	Error       string
	StartedAt   sql.NullTime
}

type CharacterSkill struct {
	ID                 int64
	ActiveSkillLevel   int64
	CharacterID        int64
	EveTypeID          int64
	SkillPointsInSkill int64
	TrainedSkillLevel  int64
}

type CharacterSkillqueueItem struct {
	ID              int64
	CharacterID     int64
	EveTypeID       int64
	FinishDate      sql.NullTime
	FinishedLevel   int64
	LevelEndSp      sql.NullInt64
	LevelStartSp    sql.NullInt64
	QueuePosition   int64
	StartDate       sql.NullTime
	TrainingStartSp sql.NullInt64
}

type CharacterToken struct {
	ID           int64
	AccessToken  string
	CharacterID  int64
	ExpiresAt    time.Time
	RefreshToken string
	TokenType    string
}

type CharacterTokenScope struct {
	ID               int64
	CharacterTokenID int64
	ScopeID          int64
}

type CharacterWalletJournalEntry struct {
	ID            int64
	Amount        float64
	Balance       float64
	CharacterID   int64
	ContextID     int64
	ContextIDType string
	Date          time.Time
	Description   string
	FirstPartyID  sql.NullInt64
	RefID         int64
	Reason        string
	RefType       string
	SecondPartyID sql.NullInt64
	Tax           float64
	TaxReceiverID sql.NullInt64
}

type CharacterWalletJournalEntryFirstParty struct {
	ID       sql.NullInt64
	Category sql.NullString
	Name     sql.NullString
}

type CharacterWalletJournalEntrySecondParty struct {
	ID       sql.NullInt64
	Category sql.NullString
	Name     sql.NullString
}

type CharacterWalletJournalEntryTaxReceiver struct {
	ID       sql.NullInt64
	Category sql.NullString
	Name     sql.NullString
}

type CharacterWalletTransaction struct {
	ID            int64
	CharacterID   int64
	ClientID      int64
	Date          time.Time
	EveTypeID     int64
	IsBuy         bool
	IsPersonal    bool
	JournalRefID  int64
	LocationID    int64
	Quantity      int64
	TransactionID int64
	UnitPrice     float64
}

type Dictionary struct {
	ID    int64
	Key   string
	Value []byte
}

type EveCategory struct {
	ID          int64
	Name        string
	IsPublished bool
}

type EveCharacter struct {
	AllianceID     sql.NullInt64
	Birthday       time.Time
	CorporationID  int64
	Description    string
	Gender         string
	FactionID      sql.NullInt64
	ID             int64
	Name           string
	RaceID         int64
	SecurityStatus float64
	Title          string
}

type EveCharacterAlliance struct {
	ID       sql.NullInt64
	Category sql.NullString
	Name     sql.NullString
}

type EveCharacterFaction struct {
	ID       sql.NullInt64
	Category sql.NullString
	Name     sql.NullString
}

type EveConstellation struct {
	ID          int64
	EveRegionID int64
	Name        string
}

type EveDogmaAttribute struct {
	ID           int64
	DefaultValue float64
	Description  string
	DisplayName  string
	IconID       int64
	Name         string
	IsHighGood   bool
	IsPublished  bool
	IsStackable  bool
	UnitID       int64
}

type EveEntity struct {
	ID       int64
	Category string
	Name     string
}

type EveGroup struct {
	ID            int64
	EveCategoryID int64
	Name          string
	IsPublished   bool
}

type EveLocation struct {
	ID               int64
	EveSolarSystemID sql.NullInt64
	EveTypeID        sql.NullInt64
	Name             string
	OwnerID          sql.NullInt64
	UpdatedAt        time.Time
}

type EveMarketPrice struct {
	TypeID        int64
	AdjustedPrice float64
	AveragePrice  float64
}

type EveRace struct {
	ID          int64
	Description string
	Name        string
}

type EveRegion struct {
	ID          int64
	Description string
	Name        string
}

type EveShipSkill struct {
	ID          int64
	Rank        int64
	ShipTypeID  int64
	SkillTypeID int64
	SkillLevel  int64
}

type EveSolarSystem struct {
	ID                 int64
	EveConstellationID int64
	Name               string
	SecurityStatus     float64
}

type EveType struct {
	ID             int64
	EveGroupID     int64
	Capacity       float64
	Description    string
	GraphicID      int64
	IconID         int64
	IsPublished    bool
	MarketGroupID  int64
	Mass           float64
	Name           string
	PackagedVolume float64
	PortionSize    int64
	Radius         float64
	Volume         float64
}

type EveTypeDogmaAttribute struct {
	ID               int64
	DogmaAttributeID int64
	EveTypeID        int64
	Value            float64
}

type EveTypeDogmaEffect struct {
	ID            int64
	DogmaEffectID int64
	EveTypeID     int64
	IsDefault     bool
}

type GeneralSectionStatus struct {
	ID          int64
	SectionID   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ContentHash string
	CompletedAt sql.NullTime
	Error       string
	StartedAt   sql.NullTime
}

type Scope struct {
	ID   int64
	Name string
}
