// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mail_labels.sql

package queries

import (
	"context"
	"strings"
)

const createMailLabel = `-- name: CreateMailLabel :one
INSERT INTO mail_labels (
    color,
    name,
    unread_count,
    my_character_id,
    label_id
)
VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, my_character_id, color, label_id, name, unread_count
`

type CreateMailLabelParams struct {
	Color         string
	Name          string
	UnreadCount   int64
	MyCharacterID int64
	LabelID       int64
}

func (q *Queries) CreateMailLabel(ctx context.Context, arg CreateMailLabelParams) (MailLabel, error) {
	row := q.db.QueryRowContext(ctx, createMailLabel,
		arg.Color,
		arg.Name,
		arg.UnreadCount,
		arg.MyCharacterID,
		arg.LabelID,
	)
	var i MailLabel
	err := row.Scan(
		&i.ID,
		&i.MyCharacterID,
		&i.Color,
		&i.LabelID,
		&i.Name,
		&i.UnreadCount,
	)
	return i, err
}

const deleteObsoleteMailLabels = `-- name: DeleteObsoleteMailLabels :exec
DELETE FROM mail_labels
WHERE mail_labels.my_character_id = ?
AND id NOT IN (
    SELECT mail_label_id
    FROM mail_mail_labels
    JOIN mails ON mails.id = mail_mail_labels.mail_id
    WHERE mail_labels.my_character_id = ?
)
`

type DeleteObsoleteMailLabelsParams struct {
	MyCharacterID   int64
	MyCharacterID_2 int64
}

func (q *Queries) DeleteObsoleteMailLabels(ctx context.Context, arg DeleteObsoleteMailLabelsParams) error {
	_, err := q.db.ExecContext(ctx, deleteObsoleteMailLabels, arg.MyCharacterID, arg.MyCharacterID_2)
	return err
}

const getMailLabel = `-- name: GetMailLabel :one
SELECT id, my_character_id, color, label_id, name, unread_count
FROM mail_labels
WHERE my_character_id = ? AND label_id = ?
`

type GetMailLabelParams struct {
	MyCharacterID int64
	LabelID       int64
}

func (q *Queries) GetMailLabel(ctx context.Context, arg GetMailLabelParams) (MailLabel, error) {
	row := q.db.QueryRowContext(ctx, getMailLabel, arg.MyCharacterID, arg.LabelID)
	var i MailLabel
	err := row.Scan(
		&i.ID,
		&i.MyCharacterID,
		&i.Color,
		&i.LabelID,
		&i.Name,
		&i.UnreadCount,
	)
	return i, err
}

const listMailLabelsByIDs = `-- name: ListMailLabelsByIDs :many
SELECT id, my_character_id, color, label_id, name, unread_count
FROM mail_labels
WHERE my_character_id = ? AND label_id IN (/*SLICE:ids*/?)
`

type ListMailLabelsByIDsParams struct {
	MyCharacterID int64
	Ids           []int64
}

func (q *Queries) ListMailLabelsByIDs(ctx context.Context, arg ListMailLabelsByIDsParams) ([]MailLabel, error) {
	query := listMailLabelsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.MyCharacterID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailLabel
	for rows.Next() {
		var i MailLabel
		if err := rows.Scan(
			&i.ID,
			&i.MyCharacterID,
			&i.Color,
			&i.LabelID,
			&i.Name,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailLabelsOrdered = `-- name: ListMailLabelsOrdered :many
SELECT id, my_character_id, color, label_id, name, unread_count
FROM mail_labels
WHERE my_character_id = ?
AND label_id > 8
ORDER BY name
`

func (q *Queries) ListMailLabelsOrdered(ctx context.Context, myCharacterID int64) ([]MailLabel, error) {
	rows, err := q.db.QueryContext(ctx, listMailLabelsOrdered, myCharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailLabel
	for rows.Next() {
		var i MailLabel
		if err := rows.Scan(
			&i.ID,
			&i.MyCharacterID,
			&i.Color,
			&i.LabelID,
			&i.Name,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrCreateMailLabel = `-- name: UpdateOrCreateMailLabel :one
INSERT INTO mail_labels (
    my_character_id,
    label_id,
    color,
    name,
    unread_count
)
VALUES (
    ?1, ?2, ?3, ?4, ?5
)
ON CONFLICT(my_character_id, label_id) DO
UPDATE SET
    color = ?3,
    name = ?4,
    unread_count = ?5
WHERE my_character_id = ?1
AND label_id = ?2
RETURNING id, my_character_id, color, label_id, name, unread_count
`

type UpdateOrCreateMailLabelParams struct {
	MyCharacterID int64
	LabelID       int64
	Color         string
	Name          string
	UnreadCount   int64
}

func (q *Queries) UpdateOrCreateMailLabel(ctx context.Context, arg UpdateOrCreateMailLabelParams) (MailLabel, error) {
	row := q.db.QueryRowContext(ctx, updateOrCreateMailLabel,
		arg.MyCharacterID,
		arg.LabelID,
		arg.Color,
		arg.Name,
		arg.UnreadCount,
	)
	var i MailLabel
	err := row.Scan(
		&i.ID,
		&i.MyCharacterID,
		&i.Color,
		&i.LabelID,
		&i.Name,
		&i.UnreadCount,
	)
	return i, err
}
