// Code generated by "stringer -type=NodeCategory"; DO NOT EDIT.

package asset

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeUndefined-0]
	_ = x[NodeAsset-1]
	_ = x[NodeAssetSafety-2]
	_ = x[NodeCargoBay-3]
	_ = x[NodeDroneBay-4]
	_ = x[NodeFighterBay-5]
	_ = x[NodeFitting-6]
	_ = x[NodeFrigateEscapeBay-7]
	_ = x[NodeFuelBay-8]
	_ = x[NodeImpounded-9]
	_ = x[NodeInSpace-10]
	_ = x[NodeItemHangar-11]
	_ = x[NodeLocation-12]
	_ = x[NodeOffice1-13]
	_ = x[NodeOffice2-14]
	_ = x[NodeOffice3-15]
	_ = x[NodeOffice4-16]
	_ = x[NodeOffice5-17]
	_ = x[NodeOffice6-18]
	_ = x[NodeOffice7-19]
	_ = x[NodeShipHangar-20]
	_ = x[NodeDeliveries-21]
	_ = x[NodeOther-22]
}

const _NodeCategory_name = "NodeUndefinedNodeAssetNodeAssetSafetyNodeCargoBayNodeDroneBayNodeFighterBayNodeFittingNodeFrigateEscapeBayNodeFuelBayNodeImpoundedNodeInSpaceNodeItemHangarNodeLocationNodeOffice1NodeOffice2NodeOffice3NodeOffice4NodeOffice5NodeOffice6NodeOffice7NodeShipHangarNodeDeliveriesNodeOther"

var _NodeCategory_index = [...]uint16{0, 13, 22, 37, 49, 61, 75, 86, 106, 117, 130, 141, 155, 167, 178, 189, 200, 211, 222, 233, 244, 258, 272, 281}

func (i NodeCategory) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeCategory_index)-1 {
		return "NodeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeCategory_name[_NodeCategory_index[idx]:_NodeCategory_index[idx+1]]
}
