# Main workflow for testing and deploying

name: CI

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc libgl1-mesa-dev xorg-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  package_linux:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc libgl1-mesa-dev xorg-dev

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Package Fyne app
      run: fyne package -os linux

    - uses: actions/upload-artifact@v4
      with:
        name: evebuddy-linux
        path: Eve Buddy.tar.xz
        if-no-files-found: error
        overwrite: true

  package_windows:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        update: true

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Dependencies
      run: >
        pacman -Syu &&
        pacman --noconfirm -S mingw-w64-x86_64-toolchain mingw-w64-x86_64-mpv

    - name: Build
      run: go build

    - name: Install Fyne tool
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Package
      run: fyne package -os windows

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: evebuddy-windows
        path: Eve Buddy.exe
        if-no-files-found: error
        overwrite: true

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [package_linux, package_windows]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Eve Buddy.tar.xz
          Eve Buddy.exe